### ISSUE TITLE
"npm i" don't work ?

### ISSUE THREAD

**Issue by flesage-000** [AaronNGray/vanilla-ts-wheel-zoom#2]
Hello,

i'm trying to install using `npm i vanilla-ts-wheel-zoom`

but receive **404** error

here is the log:
```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\MAGE\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@9.8.0
2 info using node@v18.16.1
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\MAGE\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:H:\websites\aoc-paradise\nextjs\aoc-paradise-nextjs\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\MAGE\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\MAGE\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 11ms
17 timing npm:load:configload Completed in 11ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm i vanilla-ts-wheel-zoom
22 verbose argv "i" "vanilla-ts-wheel-zoom"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:C:\Users\MAGE\AppData\Local\npm-cache\_logs\2024-03-26T16_50_00_928Z-
26 verbose logfile C:\Users\MAGE\AppData\Local\npm-cache\_logs\2024-03-26T16_50_00_928Z-debug-0.log
27 timing npm:load:logFile Completed in 11ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 55ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 3 files
33 timing idealTree:init Completed in 439ms
34 timing idealTree:userRequests Completed in 2ms
35 silly idealTree buildDeps
36 silly fetch manifest vanilla-ts-wheel-zoom@*
37 silly logfile error removing log file C:\Users\MAGE\AppData\Local\npm-cache\_logs\2024-03-26T14_30_48_920Z-debug-0.log [Error: EPERM: operation not permitted, lstat 'C:\Users\MAGE\AppData\Local\npm-cache\_logs\2024-03-26T14_30_48_920Z-debug-0.log'] {
37 silly logfile   errno: -4048,
37 silly logfile   code: 'EPERM',
37 silly logfile   syscall: 'lstat',
37 silly logfile   path: 'C:\\Users\\MAGE\\AppData\\Local\\npm-cache\\_logs\\2024-03-26T14_30_48_920Z-debug-0.log'
37 silly logfile }
38 silly logfile done cleaning log files
39 timing arborist:ctor Completed in 1ms
40 http fetch GET 404 https://registry.npmjs.org/vanilla-ts-wheel-zoom 330ms (cache skip)
41 http fetch GET 404 https://registry.npmjs.org/vanilla-ts-wheel-zoom 31ms (cache skip)
42 silly placeDep ROOT vanilla-ts-wheel-zoom@ OK for: nextjs@0.1.293 want: *
43 timing idealTree:#root Completed in 371ms
44 timing idealTree:node_modules/vanilla-ts-wheel-zoom Completed in 0ms
45 timing idealTree:buildDeps Completed in 372ms
46 timing idealTree:fixDepFlags Completed in 16ms
47 timing idealTree Completed in 830ms
48 timing command:i Completed in 837ms
49 verbose stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/vanilla-ts-wheel-zoom - Not found
49 verbose stack     at C:\Users\MAGE\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-fetch\lib\check-response.js:95:15
49 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
49 verbose stack     at async RegistryFetcher.packument (C:\Users\MAGE\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:87:19)
49 verbose stack     at async RegistryFetcher.manifest (C:\Users\MAGE\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:118:23)
49 verbose stack     at async #nodeFromEdge (C:\Users\MAGE\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1049:19)
49 verbose stack     at async #buildDepStep (C:\Users\MAGE\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:917:11)
49 verbose stack     at async Arborist.buildIdealTree (C:\Users\MAGE\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:196:7)
49 verbose stack     at async Promise.all (index 1)
49 verbose stack     at async Arborist.reify (C:\Users\MAGE\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:159:5)
49 verbose stack     at async Install.exec (C:\Users\MAGE\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:149:5)
50 verbose statusCode 404
51 verbose pkgid vanilla-ts-wheel-zoom@*
52 verbose cwd H:\websites\aoc-paradise\nextjs\aoc-paradise-nextjs
53 verbose Windows_NT 10.0.19045
54 verbose node v18.16.1
55 verbose npm  v9.8.0
56 error code E404
57 error 404 Not Found - GET https://registry.npmjs.org/vanilla-ts-wheel-zoom - Not found
58 error 404
59 error 404  'vanilla-ts-wheel-zoom@*' is not in this registry.
60 error 404
60 error 404 Note that you can also install from a
61 error 404 tarball, folder, http url, or git url.
62 verbose exit 1
63 timing npm Completed in 1246ms
64 verbose unfinished npm timer reify 1711471801330
65 verbose unfinished npm timer reify:loadTrees 1711471801334
66 verbose code 1
67 error A complete log of this run can be found in: C:\Users\MAGE\AppData\Local\npm-cache\_logs\2024-03-26T16_50_00_928Z-debug-0.log
```

**Comment by evoactivity** [comment]
@AaronNGray This fork is only useful if people can actually install the project in the expected way. Can you please publish this to npm.
